[tool.pytest.ini_options]
addopts = "--splitting-algorithm=least_duration"
minversion = "7.0"
testpaths = [
    "tests/unit",
    "tests/e2e",
    "tests/consistency",
]
markers = [
    "quick: test takes less than 100 ms",
    "kinda_slow: test takes up to 2s",
    "slow: test takes more than 2s",
    "todo: the test is not implemented or needs work",
    "no_semgrep_cli: this test doesn't invoke the semgrep CLI or osemgrep",
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py37, py38, py39, py310, py311

[testenv]
allowlist_externals = pipenv
commands =
    pipenv install --dev
    pipenv run pytest -n auto -vv --tb=short
setenv =
    # suppress a pipenv warning about using the active env
    PIPENV_VERBOSITY = -1
"""

[tool.ruff]
target-version = "py37"
extend-exclude = ["external", "tests/e2e/targets"]
select = [
  "B",
  "C4",
  "E7", "E9",
  "EXE",
  "I",
  "ICN",
  "W",
  "F",
  "PT",
  "RUF",
  # uncomment below line when new ruff is bundled in vscode extension
  # "SIM",
  "UP",
]
ignore = [
  # TODO: Fix raising inside exception handler
  "B904",
  # TODO: lru_cache on methods
  "B019",
  # uncomment below lines when new ruff is bundled in vscode extension
  # TODO: flatten if conditions
  # "SIM102",
  # TODO: use contextlib.suppress
  # "SIM105",
  # probably never enable `or` branch merging cause of readability
  # "SIM114",
  # TODO: use file open context manager
  # "SIM115",
]
allowed-confusables = ["×"]

[tool.ruff.isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]
