runs:
  - name: simple-mvc-app
    repos:
      - url: git@github.com:returntocorp/simple-mvc-app.git
        commit_hash: 336e453346e6abf73aa8522bd362eaa358c17303
    rule_configs:
      - rules/deepsemgrep-sqli-rules.yaml
    opts: [--pro]
