name: build-test-javascript

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-semgrep-js:
    name: Build Semgrep.js
    runs-on: ubuntu-latest
    container: returntocorp/ocaml:ubuntu-2023-04-03
    # We need this hack because GHA tampers with the HOME in container
    # and this does not play well with 'opam' installed in /root
    env:
      HOME: /root
    steps:
      - name: Make checkout speedy
        run: git config --global fetch.parallel 50
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build semgrep
        run: |
          eval $(opam env)

          # TODO: figure out why the opam install eats shit on ubuntu
          #make install-deps-for-semgrep-core

          (cd libs/ocaml-tree-sitter-core && ./configure && ./scripts/install-tree-sitter-lib)
          . libs/ocaml-tree-sitter-core/tree-sitter-config.sh
          ln -s $TREESITTER_INCDIR/tree_sitter /usr/include/tree_sitter
          echo "Building ocaml..."
          dune build js/engine -j 4 --profile=release

          dune build js/languages/python -j 4 --profile=release
      - uses: actions/upload-artifact@v3
        with:
          name: semgrep-js-ocaml-build
          path: |
            _build/default/js/engine/dist/*
            _build/default/js/languages/*/dist/*

  build-npm-packages:
    name: Build NPM packages
    needs: [build-semgrep-js]
    runs-on: ubuntu-latest
    container: emscripten/emsdk:3.1.36
    strategy:
      fail-fast: true
      matrix:
        package:
          - engine
          - languages/go
          - languages/lua
          - languages/python
    # We need this hack because GHA tampers with the HOME in container
    # and this does not play well with 'opam' installed in /root
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: semgrep-js-ocaml-build
      - name: Build semgrep
        run: |
          echo "Installing a modern version of node..."
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install --lts

          echo "Building JS + WASM..."
          make -C js/${{ matrix.package }}

          echo "Testing..."
          make -C js/${{ matrix.package }} test
