name: build-test-manylinux-aarch64

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      wheel-artifact-name:
        description: "The name under which the wheel artifact was stored"
        value: ${{ jobs.build-wheel.outputs.wheel-artifact-name }}

env:
  WHEEL_ARTIFACT_NAME: manylinux-aarch64-wheel

jobs:
  build-wheel:
    name: Build and test Semgrep python wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      wheel-artifact-name: ${{ steps.wheel-artifact-name.outputs.wheel-artifact-name }}
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: depot/setup-action@v1
      - name: Build and test python wheel
        id: build-semgrep-wheel
        uses: depot/build-push-action@v1.7.1
        with:
          project: fhmxj6w9z8
          platforms: linux/arm64
          outputs: type=docker,dest=/tmp/image.tar
          target: semgrep-wheel
          buildx-fallback: true
      - name: Extract wheel from docker image
        run: |
          docker load --input /tmp/image.tar
          docker run --platform linux/arm64 --rm ${{ steps.build-semgrep-wheel.outputs.imageid }} zip -r - dist > /tmp/dist.zip
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.WHEEL_ARTIFACT_NAME }}"
          path: /tmp/dist.zip
      - name: Set Wheel Name Output
        id: wheel-artifact-name
        run: |
          echo "wheel-artifact-name=${WHEEL_ARTIFACT_NAME}" >> $GITHUB_OUTPUT
