# This workflow builds and tests the semgrep-core binary for macOS M1
# and generates the m1-wheel for pypi.

# coupling: if you modify this file, modify also build-test-osx-x86.yaml
# This file is mostly a copy-paste of build-test-osx-x86.yaml
name: build-test-osx-m1

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: false
        type: boolean
        default: true

jobs:
  # build-core-m1:
  #   name: Build the OSX M1 binaries
  #   #TODO? if the use of the GHA-hosted runner works well in build-test-osx-x86.yaml,
  #   # we might as well move out of a self-hosted runner for M1 too.
  #   # This would remove the need for those ugly hard cleanup below because
  #   # our self-hosted runner builds are not "hermetic".
  #   runs-on:
  #     [
  #       "self-hosted",
  #       "macOS",
  #       "ARM64",
  #       "ghcr.io/cirruslabs/macos-monterey-xcode:latest",
  #     ]
  #   env:
  #     OPAM_SWITCH_NAME: "4.14.0"
  #   steps:
  #     - name: Setup runner directory
  #       run: |
  #         sudo mkdir /Users/runner
  #         sudo chown admin:staff /Users/runner
  #         sudo chmod 750 /Users/runner
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.11"
  #     - name: Dump info
  #       run: |
  #         echo $PATH
  #         which pip3
  #         pip3 --version
  #         which python3
  #         python3 --version
  #         ls -hal /Users/runner/hostedtoolcache/Python/3.11.4/arm64/bin
  #         # ls -hal /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #     # Note that this action handles both cache read and cache write.
  #     # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows for more information on GHA caching.
  #     - name: Cache Opam
  #       id: cache-opam
  #       uses: actions/cache@v3
  #       if: ${{ inputs.use-cache }}
  #       env:
  #         SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
  #       with:
  #         path: ~/.opam
  #         key: "${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME }}-opam-deps"
  #     - name: Install dependencies
  #       run: |
  #         ./scripts/osx-setup-for-release.sh "${{ env.OPAM_SWITCH_NAME }}"
  #     - name: Compile semgrep
  #       run: |
  #         opam exec -- make core
  #         mkdir -p artifacts
  #         cp ./bin/semgrep-core artifacts
  #         zip -r artifacts.zip artifacts
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: artifacts.zip
  #         name: semgrep-m1-${{ github.sha }}
  #     - name: Save Semgrep Core Binary
  #       id: cache-semgrep-core
  #       uses: actions/cache/save@v3
  #       with:
  #         path: artifacts.zip
  #         key: osx-m1-semgrep-core-VzlGZQINFX2

  build-wheels-m1:
    runs-on: [
        "self-hosted",
        "macOS",
        "ARM64",
        # "ghcr.io/cirruslabs/macos-monterey-base:latest",
      ]
    steps:
      # - name: Setup runner directory
      #   run: |
      #     sudo mkdir /Users/runner
      #     sudo chown admin:staff /Users/runner
      #     sudo chmod 750 /Users/runner
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.11"
      # - name: Brew Update & Install Python
      #   run: |
      #     brew update
      #     brew install python@3.11
      - uses: actions/checkout@v3
        # with:
        #   submodules: true
      - name: Restore Semgrep Core Binary
        id: cache-semgrep-core
        uses: actions/cache/restore@v3
        with:
          path: artifacts.zip
          key: osx-m1-semgrep-core-VzlGZQINFX2
      - run: |
          unzip artifacts.zip
          cp artifacts/semgrep-core cli/src/semgrep/bin
          which pip3
          pip3 --version
          which python3
          python3 --version
          pip3 list
          ./scripts/build-wheels.sh
      - uses: actions/upload-artifact@v3
        with:
          path: cli/dist.zip
          name: m1-wheel
