# This workflow builds and tests the semgrep-core binary for macOS arm64
# and generates the arm64-wheel for pypi.

# coupling: if you modify this file, modify also build-test-osx-arm64.yaml
name: build-test-osx-x86

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: false
        type: boolean
        default: true

jobs:
  build-osx-arm64:
    uses: ./.github/workflows/build-test-osx.yaml
    secrets: inherit
    with:
      runs-on: "['macos-12']"
      architecture: "x86"
      wheel-artifact-name: osx-x86-wheel
      wheel-plat-name: macosx_10_14_x86_64
      use-cache: ${{ inputs.use-cache }}
