# This workflow builds and tests the semgrep-core binary for macOS arm64
# and generates the arm64-wheel for pypi.

# coupling: if you modify this file, modify also build-test-osx-x86.yaml
# This file is mostly a copy-paste of build-test-osx-x86.yaml
name: build-test-osx-arm64

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: true
        type: boolean
        default: true
  workflow_call:
    inputs:
      use-cache:
        description: "Use Opam Cache - uncheck the box to disable use of the opam cache, meaning a long-running but completely from-scratch build."
        required: false
        type: boolean
        default: true
    outputs:
      wheel-artifact-name:
        description: "The name under which the wheel artifact was stored"
        value: ${{ jobs.wheel-name.outputs.wheel-artifact-name }}

env:
  WHEEL_ARTIFACT_NAME: osx-arm64-wheel

jobs:
  wheel-name:
    runs-on: ubuntu-22.04
    outputs:
      wheel-artifact-name: ${{ steps.wheel-artifact-name.outputs.wheel-artifact-name }}
    steps:
      - name: Set Wheel Name Output
        id: wheel-artifact-name
        run: |
          echo "wheel-artifact-name=${WHEEL_ARTIFACT_NAME}" >> $GITHUB_OUTPUT
  build-core-osx-arm64:
    uses: ./.github/workflows/build-test-osx.yaml
    secrets: inherit
    needs: [wheel-name]
    with:
      runs-on: "['self-hosted','macOS','ARM64','ghcr.io/cirruslabs/macos-monterey-xcode:latest']"
      architecture: "arm64"
      wheel-artifact-name: ${{ needs.wheel-name.outputs.wheel-artifact-name }}
      use-cache: ${{ inputs.use-cache }}
