name: Crons to run periodically for Semgrep
on:
  push:
    branches:
      - crons

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: pwd
  update-semgrep-rules-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls semgrep-core/tests/semgrep-rules
      - run: cd semgrep-core/tests/semgrep-rules; git checkout develop; git pull
