name: Crons to run periodically for Semgrep
on:
  push:
    branches:
      - crons

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: pwd
