name: Crons to run periodically for Semgrep
on:
  push:
    branches:
      - crons

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: pwd
  update-semgrep-rules-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cd semgrep-core/tests/semgrep-rules; git checkout develop; git pull
      - run: echo MODIF >> README.md
      - run: git status
      - run: git checkout -b crons_update_semgrep_rules
      - run: git commit -a -m"update semgrep rules"
      - run: git push origin crons_update_semgrep_rules
      - run: hub pull-request -b develop
