name: crons
on:
  push:
    branches:
      - crons

jobs:
  update-semgrep-rules-submodule:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: cd semgrep-core/tests/semgrep-rules; git checkout develop; git pull
      - run: echo MODIF >> README.md
      - run: git status
      - run: git checkout -b crons_update_semgrep_rules
      # from https://ao.ms/how-to-use-git-commit-in-github-actions/
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: git commit -a -m"update semgrep rules"
      - run: git push origin crons_update_semgrep_rules
      - run: gh pr create --title 'Cron - update semgrep-rules' --base develop --reviewer aryx
