name: Crons to run periodically for Semgrep
on:
  push:
    branches:
      - crons

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: pwd
  update-semgrep-rules-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: ls -l semgrep-core/tests/
      - run: cd semgrep-core/tests/semgrep-rules; git checkout develop; git pull
