# This workflow performs additional tasks on a PR when
# someone (or start-release.yml) push to a vXXX branch.
# Those tasks are to push a new develop docker image, create
# release artifacts with the Linux and MacOS semgrep packages,
# update PyPy and homebrew, etc.

name: tests

on:
  workflow_dispatch:
  push:
    branches:
      # Sequence of patterns matched against refs/tags
      - "**-test-release"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  test-macos-release:
    name: test macOS release
    runs-on: macos-12
    steps:
      - name: install package
        run: pip3 install semgrep==1.5.1
      - name: test package
        run: |
          otool -L /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/semgrep/bin/semgrep-core | grep /Users/
          retVal=$?
          if [ $retVal -ne 0 ]; then
            echo "Error: semgrep-core has been linked with a user-specific libary which will not be available on other machines."
            exit 1;
          fi
